service: oauth2-jwt-serverless-aws-apigateway # NOTE: update this with your service name

plugins:
  - serverless-offline

custom:
  serverless-offline:
    host: 0.0.0.0

provider:
  name: aws
  runtime: nodejs6.10

functions:

  token-signature:
    handler: authorizer/authorizer-token-signature.jwtverify

  test:
    handler: lambda/handler.handler
    events:
      - http:
          path: /
          method: any
          integration: lambda
          authorizer: token-signature
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token

